### PR TITLE
Fix #682

### LINKED ISSUE #682: Report tabulator generator intermittently creates empty tabulator class
Report tabulator generator intermittently creates empty `ESMAEMIRMarginReportTabulator` class.

1) Empty generated `ESMAEMIRMarginReportTabulator` (see (4) for correctly generated)
* Note that the constructor parameter is (incorrectly) the same as the class, causing a Guice circular dependency (see (2))
```
public class ESMAEMIRMarginReportTabulator implements Tabulator<ESMAEMIRMarginReport> {
        private final ESMAEMIRMarginReportTabulator tabulator;

        @Inject
        public ESMAEMIRMarginReportTabulator(ESMAEMIRMarginReportTabulator tabulator) {
                this.tabulator = tabulator;
        }

        @Override
        public List<Field> getFields() {
                return tabulator.getFields();
        }

        @Override
        public List<FieldValue> tabulate(ESMAEMIRMarginReport report) {
                return tabulator.tabulate(report);
        }
}
```

2) Guice circular dependency logs 
```
ERROR [2023-10-26 20:54:08,897] [dw-90 - POST /core-rw/api/report/simon_local_303188572/DRR116/run-report/Collateral/drr.regulation.esma.emir.refit.margin.%3CESMA%20EMIR%20Margin%3E] [simon_local_303188572] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: d14e82d41f308bd1
! com.google.inject.ProvisionException: Unable to provision, see the following errors:
! 
! 1) [Guice/CanNotProxyClass]: Tried proxying ESMAEMIRMarginReportTabulator to support a circular dependency, but it is not an interface.
!   at ESMAEMIRMarginReportTabulator.<init>(Unknown Source)
!       \_ for 1st parameter
!   while locating ESMAEMIRMarginReportTabulator
! 
! Learn more:
!   https://github.com/google/guice/wiki/CAN_NOT_PROXY_CLASS
! 
! 1 error
! 
! ======================
! Full classname legend:
! ======================
! ESMAEMIRMarginReportTabulator: "drr.regulation.esma.emir.refit.margin.reports.ESMAEMIRMarginReportTabulator"
! ========================
! End of classname legend:
! ========================
! 
! at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
! at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1103)
! at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138)
! at com.regnosys.rosetta.report.services.ReportFunctionAndTabulator$ReportFunctionAndTabulatorBuilder.getTabulator(ReportFunctionAndTabulator.java:57)
! at com.regnosys.rosetta.report.services.ReportFunctionAndTabulator$ReportFunctionAndTabulatorBuilder.build(ReportFunctionAndTabulator.java:39)
! at com.regnosys.rosetta.report.services.ReportRunServiceImpl.switchBetweenReportRunners(ReportRunServiceImpl.java:76)
! at com.regnosys.rosetta.report.resources.ReportResource.run(ReportResource.java:151)
! ... 78 common frames omitted
```

3) Generation logs
image

4) Correctly generated `ESMAEMIRMarginReportTabulator`
```
public class ESMAEMIRMarginReportTabulator implements Tabulator<ESMAEMIRMarginReport> {
	private final Field partiesToTheDerivativeField;
	private final Field collateralField;
	
	private final PartiesToTheDerivativeTabulator partiesToTheDerivativeTabulator;
	private final CollateralReportTabulator collateralReportTabulator;
	
	@Inject
	public ESMAEMIRMarginReportTabulator(PartiesToTheDerivativeTabulator partiesToTheDerivativeTabulator, CollateralReportTabulator collateralReportTabulator) {
		this.partiesToTheDerivativeTabulator = partiesToTheDerivativeTabulator;
		this.collateralReportTabulator = collateralReportTabulator;
		this.partiesToTheDerivativeField = new FieldImpl(
			"partiesToTheDerivative",
			false,
			Optional.empty(),
			Optional.empty(),
			partiesToTheDerivativeTabulator.getFields()
		);
		this.collateralField = new FieldImpl(
			"collateral",
			false,
			Optional.empty(),
			Optional.empty(),
			collateralReportTabulator.getFields()
		);
	}
	
	@Override
	public List<Field> getFields() {
		return Arrays.asList(partiesToTheDerivativeField, collateralField);
	}
	
	@Override
	public List<FieldValue> tabulate(ESMAEMIRMarginReport report) {
		Optional<List<FieldValue>> partiesToTheDerivative = Optional.ofNullable(report.getPartiesToTheDerivative())
			.map(x -> partiesToTheDerivativeTabulator.tabulate(x));
		Optional<List<FieldValue>> collateral = Optional.ofNullable(report.getCollateral())
			.map(x -> collateralReportTabulator.tabulate(x));
		return Arrays.asList(
			new NestedFieldValueImpl(partiesToTheDerivativeField, partiesToTheDerivative),
			new NestedFieldValueImpl(collateralField, collateral)
		);
	}
}
```

### PR DESCRIPTION
**Pull request by SimonCockx**
Fixes #682 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/types/JavaTypeTranslator.java [hunk 1]
```diff
@@ -116,24 +112,24 @@ public JavaClass<RosettaFunction> toFunctionJavaClass(Function func) {
...
 	}
-	public JavaClass<Tabulator> toTabulatorJavaClass(Data type, Optional<RosettaExternalRuleSource> ruleSource) {
+	public JavaClass<Tabulator<?>> toTabulatorJavaClass(Data type, Optional<RosettaExternalRuleSource> ruleSource) {
 		ModelSymbolId typeId = getSymbolId(type);
 		Optional<RosettaExternalRuleSource> containingRuleSource = ruleSource.flatMap((rs) -> findContainingSuperRuleSource(type, rs));
 		if (containingRuleSource.isEmpty()) {
 			DottedPath packageName = typeId.getNamespace().child("reports");
-			String simpleName = typeId.getName() + "Tabulator";
-			return new GeneratedJavaClass<>(packageName, simpleName, Tabulator.class);
+			String simpleName = typeId.getName() + "TypeTabulator";
```
Comment (SimonCockx) [inline rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/types/JavaTypeTranslator.java:126]: Actual fix here...

File: rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/types/JavaTypeTranslator.java [hunk 2]
```diff
@@ -116,24 +112,24 @@ public JavaClass<RosettaFunction> toFunctionJavaClass(Function func) {
...
+			return new GeneratedJavaClass<>(packageName, simpleName, new com.fasterxml.jackson.core.type.TypeReference<Tabulator<?>>() {});
 		}
 		ModelSymbolId sourceId = getSymbolId(containingRuleSource.get());
 		DottedPath packageName = sourceId.getNamespace().child("reports");
-		String simpleName = typeId.getName() + sourceId.getName() + "Tabulator";
-		return new GeneratedJavaClass<>(packageName, simpleName, Tabulator.class);
+		String simpleName = typeId.getName() + sourceId.getName() + "TypeTabulator";
```
Comment (SimonCockx) [inline rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/types/JavaTypeTranslator.java:131]: and here.

**Review by hugohills-regnosys — APPROVED** [review]
